name: tailoredit
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12.3
  - pip=24.0
  - setuptools=70.0.0
  - wheel=0.43.0
  - certifi=2024.2.2
  - openssl=3.0.13
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - transformers==4.47.0
      - diffusers==0.31.0
      - peft==0.14.0
      - accelerate==1.2.0
      - bitsandbytes==0.45.0
      - xformers==0.0.28.post3
      - safetensors==0.4.5
      - numpy==2.1.3
      - scipy==1.14.1
      - pandas==2.2.3
      - opencv-python==4.10.0.84
      - pillow==11.0.0
      - scikit-image==0.24.0
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - jupyterlab==4.3.1
      - ipython==8.29.0
      - ipykernel==6.29.5
      - requests==2.32.3
      - beautifulsoup4==4.12.3
      - pandas==2.2.3
      - einops==0.8.0
      - black==24.4.2
      - flake8==7.1.0
      - yapf==0.43.0